### ISSUE TITLE
test-app.R fails

### ISSUE THREAD

**Issue by FrieseWoudloper** [informalr/informalr#124]
The tests in test-app.R currently fail. 

```
Warning (test-app.R:4:1): (code run outside of `test_that()`)
package 'shinytest' was built under R version 4.0.3
Backtrace:
 1. base::library(shinytest) test-app.R:4:0
 2. base:::testRversion(pkgInfo, package, pkgpath)

Failure (test-app.R:13:3): app() works
Not all shinytest scripts passed for apps/app/: mytest

Diff output:
==== mytest ====
diff "C:\\Users\\XXX\\AppData\\Local\\Temp\\RtmpID9Pyx\\shinytest-diff-33341eb3ad/mytest-expected/001.json" "C:\\Users\\XXX\\AppData\\Local\\Temp\\RtmpID9Pyx\\shinytest-diff-33341eb3ad/mytest-current/001.json"
1,13c1,13
< {
<   "input": {
< 
<   },
<   "output": {
<     "map": [
< 
<     ]
<   },
<   "export": {
< 
<   }
< }
---
> {
>   "input": {
> 
>   },
>   "output": {
>     "map": [
> 
>     ]
>   },
>   "export": {
> 
>   }
> }
```

**Comment by janclod** [comment]
Maybe this discussion could help:
https://stackoverflow.com/questions/64850430/r-shinytest-github-actions-failing-on-windows-but-passing-on-mac-and-ubuntu

**Comment by FrieseWoudloper** [comment]
I lost the warning by upgrading R to the latest version. Alas it didn't solve the error.

**Comment by FrieseWoudloper** [comment]
I seem to have solved this issue, but I don't know how. I don't see any difference between @janclod's files and mine when I compare them on Github. The only thing I can think of, is that - after I messed up Claudio's Shiny test files - I downloaded a ZIP-file containing the informalr repository and replaced the shiny test files in my local branch by the original ones from the ZIP-file.

**Comment by richelbilderbeek** [comment]
@janclod and @FrieseWoudloper: will you discuss this Issue, so it can/cannot be closed? :+1:

**Comment by FrieseWoudloper** [comment]
I reproduced this issue on my second Windows laptop: When I clone the repo in RStudio and run `devtools::test()` the test in test-app.R fails. When I subsequently download the repo as a ZIP-file, and copy the map `/tests/testthat/apps/app/tests/shinytest/mytest-expected` into my local repository, it passes the test.

**Comment by FrieseWoudloper** [comment]
I would like to create a smaller, reproducible example and submit an issue to the creators of the shinytest package.

**Comment by FrieseWoudloper** [comment]
Reproducible example: https://github.com/FrieseWoudloper/reprexshinytest
Issue: https://github.com/rstudio/shinytest/issues/371

**Comment by janclod** [comment]
Note to myself
https://github.com/r-lib/actions/tree/master/examples#test-coverage-workflow
Try to add this to latest commit on claudio branch. Now testing seems to work but codecoverage has issues.

**Comment by janclod** [comment]
> Reproducible example: https://github.com/FrieseWoudloper/reprexshinytest
> Issue: [rstudio/shinytest#371](https://github.com/rstudio/shinytest/issues/371)

Good effort! @FrieseWoudloper
