### ISSUE TITLE
No test for check whether destination directory exists in get_bridge_openings.R

### ISSUE THREAD

**Issue by FrieseWoudloper** [informalr/informalr#133]
Add a test for this line of code in get_bridge_openings.R:

` if (!file.exists(destdir)) dir.create(destdir, recursive = TRUE)`

We're aiming voor 100% code coverage :1st_place_medal:

**Comment by FrieseWoudloper** [comment]
Actually I think the check (and thus the test) is not necessary.

`rappdirs::user_cache_dir(appname = "informalr")` will ensure that the directory is created.

I propose to replace this code chunk:
```
    cachedir <- rappdirs::user_cache_dir(appname = "informalr")
    destdir <- file.path(cachedir, "extdata")
    if (!file.exists(destdir)) dir.create(destdir, recursive = TRUE)
```
by this line of code:
```
    destdir <- rappdirs::user_cache_dir(appname = "informalr")
```
Then there is no need to add an extra test for get_bridge_openings.R.

**Comment by richelbilderbeek** [comment]
@FrieseWoudloper: I agree with your suggestion to simplify the code as you proposed! The old code was a left-over from history.
