### ISSUE TITLE
Test in test-get_fransbianchi_github_username.R is not working

### ISSUE THREAD

**Issue by FrieseWoudloper** [informalr/informalr#137]
- Rename `test-get_fransbianchi_github_username.R` to `test-get_frans_github_username.R`
- Change this line of code `expect_equal("fransbianchi", get_fransbianchi_github_username())` and call an existing function (`get_frans_github_username()`).
- Remove  this line of code: `skip("Issue 12, Issue #12")`

**Comment by richelbilderbeek** [comment]
It would be great of @fransbianchi would fix this. He will, because he is awesome like that :+1:

**Comment by janclod** [comment]
I decided to help Frans :+1:
