### ISSUE TITLE
Bridges' coordinats must all be unique

### ISSUE THREAD

**Issue by janclod** [informalr/informalr#142]
We only check that we have no duplicate in the first row of our data frame.

See test in the test-get_bridge_openings.R file:
`    bool <- bridges$lat[1] != bridges$lat[2] || bridges$lon[1] != bridges$lon[2]
    expect_true(bool)`

Since this data frame contains data coming from some online source (possibly containing surprises!), we should loop through the whole data frame and check that every row is a unique entry.

**Comment by richelbilderbeek** [comment]
A possible solution:

 * Concatenate all values as strings (in R, use `as.character` and `paste0`), e.g '1.2 and '3.4' becomes `1.2_3.4`. Put all these results in a single vector
 * All these elements should be unique, so using `unique` (to remove duplicates) should return a vector that has the same length as the original one :+1:

**Comment by FrieseWoudloper** [comment]
We are testing for duplicate values now, but there is no code in `get_bridge_openings` that removes the duplicates or that gives an error when there are duplicates, so sometimes our test fails.
So I'm reopening this issue, because we still have to add code to `get_bridge_openings.R`.
