### ISSUE TITLE
Do we want to use pipes in our project?

### ISSUE THREAD

**Issue by FrieseWoudloper** [informalr/informalr#154]
I noticed that @bogeert uses pipes  (from the magrittr package) in his code. I also would like to use pipes, especially if we decide to proceed with the leaflet package for creating interactive maps. If we don't use pipes, we'll get a lot of repetition in the code. However, I do understand that pipes may be a challenge for team members new to R. So I would like to discuss the question whether or not to use pipes in one of our next meetings.

**Comment by richelbilderbeek** [comment]
Note to self: discuss using pipes in the next meeting. @FrieseWoudloper do you volunteer to show this to the team next week, in 5 mins max?

**Comment by FrieseWoudloper** [comment]
In our meeting of today we decided we will use pipes whenever it improves the readability and maintainability of our code.
Note that it's still okay to nest functions when the nesting is not too deep.

Also when you are using pipes, you'll need to add this to the `roxygen2` header of your functions:
`#' @importFrom magrittr "%>%"`
