### ISSUE TITLE
Break down the get_bridge_openings function

### ISSUE THREAD

**Issue by janclod** [informalr/informalr#161]
At the moment, the get_bridge_openings function does many things.

Break the function into two blocks:

1. get the data from the internet and place it into an xml object
2. extract the desired data from the xml object (leave this with the name get_bridge_openings)

**Comment by FrieseWoudloper** [comment]
I guess we were having the same thought ;-) https://github.com/informalr/informalr/issues/155

**Comment by janclod** [comment]
Yes I realized XD
