### ISSUE TITLE
Determine the project for this season democratically

### ISSUE THREAD

**Issue by richelbilderbeek** [informalr/informalr#168]
Currently, we have worked on the hiking app for half a year. It may be possible that the team would like to start working on a new project.

Here, you can suggest your project, before tomorrow/Tuesday 20:15.

At 20:15, each suggested project gets 3 minutes (max! sharp!) to be explained.

After that, we will vote for the current project (the hiking app) as well as a new project. 

You can vote as often as you would like, so we determine the project with most votes. 

At 21:00 (at latest), we will have determined the project for this season democratically.

**Comment by FrieseWoudloper** [comment]
Digital escape room

**Comment by alexinedewit** [comment]
(3D) SnackMan (details follow later)

**Comment by richelbilderbeek** [comment]
Sketch of `gggame`:

![gggame](https://user-images.githubusercontent.com/2098230/103680198-19ae5700-4f86-11eb-9d5d-0533245b55ff.png)

Details at 19:15 :+1:

**Comment by janclod** [comment]
chooseEASY

**Comment by richelbilderbeek** [comment]
It is Snackman!
