### ISSUE TITLE
Decide on what moment of the week to meet

### ISSUE THREAD

**Issue by richelbilderbeek** [informalr/informalr#2]
We need to decide on the moment of the week to meet.

Procedure: you can suggest as many timeslot as you like, as well as a rating: 3 = awesome, 2 = OK, 1 = meh, 0 = cannot.

For example:

 * Tuesday 17:00-19:00: 3 
 * Wednesday 17:00-19:00: 1
 * Saturday 17:00-19:00: 2
 * Saturday 18:00-20:00: 2 (sure, overlap is fine)
 * Sunday 10:00-22:00: 2 (sure, a wider range is fine)

Timeslots must be (sorry!) somewhere:

 * Tuesday 15:00-22:00
 * Wednesday 15:00-22:00
 * Saturday 12:00-22:00
 * Sunday 12:00-22:00

Then we pick a two-hour timeslot with the highest sum of ratings

**Comment by richelbilderbeek** [comment]
My votes:

 * Tuesday 15:00-17:00: 2
 * Tuesday 17:00-21:00: 3
 * Wednesday 15:00-21:00: 2
 * Saturday 12:00-17:00: 1
 * Saturday 17:00-22:00: 2
 * Sunday 12:00-17:00: 1
 * Sunday 17:00-22:00: 2

**Comment by richelbilderbeek** [comment]
Sent out email.

**Comment by bogeert** [comment]
Geert's votes:

My votes:

    Tuesday 15:00-17:00: 1
    Tuesday 17:00-21:00: 3
    Wednesday 15:00-21:00: 0
    Saturday 12:00-17:00: 1
    Saturday 17:00-22:00: 2
    Sunday 12:00-17:00: 1
    Sunday 17:00-22:00: 2

**Comment by AparajithaRamesh** [comment]
My votes:

Tuesday 17:00-20:00 : 3
Tuesday 20:00-22:00 : 0
Wednesday 15:00-22:00: 0
Saturday 12:00-17:00: 2
Saturday 1700-20:00: 3
Saturday 20:00-22:00: 0
Sunday 12:00-17:00: 0
Sunday 17:00-20:00: 2
Sunday 20:00-22:00: 0

**Comment by FrieseWoudloper** [comment]
Saturday 12:00-22:00 3
Sunday 12:00-22:00 3

**Comment by richelbilderbeek** [comment]
Lizzy's votes:

  * Tuesday 17:00-21:00: 3
 * Wednesday 17:00-21:00: 3
 * Saturday 12:00-22:00: 0
 * Sunday 12:00-17:00: 0
 * Sunday 17:00-22:00: 2

**Comment by fastnotfurious** [comment]
Anne's votes: 

    Tuesday 17:00-21:00: 3
    Wednesday 17:00-21:00: 3
    Saturday 12:00-22:00: 0
    Sunday 12:00-17:00: 0
    Sunday 17:00-22:00: 1

**Comment by richelbilderbeek** [comment]
Concluding: whatever our last team member Harry does, Tuesday 17:00-21:00 will be the timeslot.

All we need to do is a round to narrow this down :+1:

**Comment by richelbilderbeek** [comment]
Continue at #9
