### ISSUE TITLE
Willy: use better error message

### ISSUE THREAD

**Issue by richelbilderbeek** [informalr/informalr#37]
In `test-modulo_two_numbers.R` I find this test:
 
```
  expect_error(modulo_two_numbers("a", "b"),
               "is.numeric(a) & is.numeric(b) is not TRUE",
               fixed = TRUE)
```

In #34 I suggest to use error messages that are proper English. I encourage you to do so :+1:

**Comment by richelbilderbeek** [comment]
Note: today I will demo how to do so :+1:

**Comment by FrieseWoudloper** [comment]
Done!
