### ISSUE TITLE
Vote for the projects

### ISSUE THREAD

**Issue by richelbilderbeek** [informalr/informalr#42]
Vote for the projects. You can vote as often as you would like (including for none or all projects). The project with most votes will be worked on. These are the projects:

  1. A text adventure
  2. Build netmhcpan, an R package that predict which parts of a protein will most likely trigger an immune response
  3. A textadventure, like 1, with a secondary focus on having crime (or other) stories in the newpapers, including graphs
  4. Hiking guide to help hikers spot busy routes/stops before they embark on a hike
  5. application to rob a Swiss bank and get rich and/or divide the money to the poor
  6. COVID app. Real time see how many COVID-19 cases are in your municipality
  7. Analyze webcam data to automatically determine the crowdedness of public locations
  8- Recommender that uses predictors like an image, voice recording, time of day, etc. suggests a
      song by K3 that best matches your mood.

Vote with, for example: 1,4,6,7

Deadline for voting is next week. September 8th at approx 18:30, after a short (2 min max) talk about all projects.

**Comment by janclod** [comment]
1, 3

**Comment by FrieseWoudloper** [comment]
8- Recommender that uses predictors like an image, voice recording, time of day, etc. suggests a song by K3 that best matches your mood.

**Comment by bogeert** [comment]
6,7,8

**Comment by Lizzie-Roeble** [comment]
4, 5

**Comment by FrieseWoudloper** [comment]
1,3,4,5

**Comment by fastnotfurious** [comment]
4, 7

**Comment by richelbilderbeek** [comment]
It has become [Option 4](https://github.com/informalr/informalr/issues/8#issuecomment-684954585)

**Comment by richelbilderbeek** [comment]
Quote from Issue 4:

    Hiking guide to help hikers spot busy routes/stops before they embark on a hike. This show a somehow similar idea:
    Untitled

Edit: added:

[6:41 PM] Willy: There are open data on traffic intensities: https://www.ndw.nu/pagina/en/78/database/
[6:41 PM] Willy: Also real time data: https://www.ndw.nu/pagina/en/78/database/79/real-time_traffic_data/
