### ISSUE TITLE
Read traffic data

### ISSUE THREAD

**Issue by bogeert** [informalr/informalr#44]
Read the data on traffic intensities, for instance from NDW:
http://opendata.ndw.nu/

**Comment by richelbilderbeek** [comment]
These were suggestions from @FrieseWoudloper:

 * `https://www.ndw.nu/pagina/en/78/database/`
 *  real time data: `https://www.ndw.nu/pagina/en/78/database/79/real-time_traffic_data/`

**Comment by richelbilderbeek** [comment]
This sounds like a function called `read_ndw_nu_file`, something like:

```{r}
xml <- read_ndw_nu_file("incidents.xml.gz") # Maybe without .xml.gz?
# Do something with the parsed XML
```

**Comment by richelbilderbeek** [comment]
This Issue can be done after having added the first stub of `get_car_density` at #103

**Comment by richelbilderbeek** [comment]
Moved this to README, closing this Issue :+1:
