### ISSUE TITLE
Find related projects 

### ISSUE THREAD

**Issue by fastnotfurious** [informalr/informalr#46]
Find similar projects (probably also code); to have a basis for a start

**Comment by fastnotfurious** [comment]
Object Detection with YOLO and MobileNet SSD:

https://github.com/dannylee1020/object-detection-app

**Comment by FrieseWoudloper** [comment]
Realtime bus dashboard: https://shiny.rstudio.com/gallery/bus-dashboard.html

**Comment by richelbilderbeek** [comment]
Put all in README. Closing this one :+1:
