### ISSUE TITLE
Read public transportation data

### ISSUE THREAD

**Issue by FrieseWoudloper** [informalr/informalr#48]
Where are the stations? Where are the bus stops?
Data sources: NDOV loket (https://data.ndovloket.nl/) or OpenStreetMap (Overpass API, https://overpass-turbo.eu/)

**Comment by richelbilderbeek** [comment]
@FrieseWoudloper: is this Issue still needed? If this Issue is mostly a note, I suggest to move the sources to the README :+1:

**Comment by FrieseWoudloper** [comment]
Fixed the error, but need to merge it into develop after the build of my branch went well.
