### ISSUE TITLE
Visualize data on a map

### ISSUE THREAD

**Issue by FrieseWoudloper** [informalr/informalr#49]
We probably want to use the Leaflet package to plot thematic data (hotspots, traffic, public transportation) on a base map.
We also have to decide on which base map to use, for instance OpenStreetMap or BRTAchtergrondkaart (the official basemap of Dutch government).

**Comment by richelbilderbeek** [comment]
Hi @janclod, 

maybe the Issue [Create a stub for the Shiny app](https://github.com/informalr/informalr/issues/50) is a better starting point (tip: ask Willy to pair program this together!).

OTOH, if you have ideas what to do with this Issue, let me know which test you want to write and make come true. Else, I suggest you unassign from this Issue for now :+1:

**Comment by richelbilderbeek** [comment]
AFAICS, this Issue has been done: he have seen dots on a map. Done :+1:
