### ISSUE TITLE
Decide online meeting place

### ISSUE THREAD

**Issue by richelbilderbeek** [informalr/informalr#5]
We need to decide how to meet online.

Suggest zero, one or more suggestions of online meeting places.

`tresinformal` uses both Discord (for chat) and Google Hangouts (for group programming), so that feels the most natural to do.

Suggestion with the most votes wins.

**Comment by richelbilderbeek** [comment]
My votes: Discord, but open to suggestions

**Comment by AparajithaRamesh** [comment]
Discord!

**Comment by Neves-P** [comment]
+1 for discord 👍

**Comment by richelbilderbeek** [comment]
Discord it is. Well, it was not much of a vote really :rainbow:
