### ISSUE TITLE
Create a stub for the Shiny app

### ISSUE THREAD

**Issue by FrieseWoudloper** [informalr/informalr#50]
This is a nice study Issue: create a stub for a Shiny app that we will build to interact with the user and display the information.

 * Get a Shiny app to work. This test must pass:

```
expect_silent(run_app())
```

 * Let it display `create_map` for a picked/random setting: no user interaction for now. Use this test:

```r
skip("Only run manually, as it requires user interaction")
png_filename <- tempfile(fileext = ".png")
expect_silent(run_app(png_filename = png_filename)) # User must close the app!
expect_true(file.exist(png_filename))
```

A Dutch tutorial can be found at [https://github.com/FrieseWoudloper/shiny-workshop](https://github.com/FrieseWoudloper/shiny-workshop).

**[edit: @richelbilderbeek added some example tests]**

**Comment by richelbilderbeek** [comment]
I think it is a good idea to show a stub of the app before putting it in Shiny.

I make it a low priority Issue, as it is too early for now. Instead, for starters, the user interface will be a vignette. I will increase priority when we are ready for something more fancy :+1:

**Comment by richelbilderbeek** [comment]
As `create_map` indeed creates an image, the first stub can be made :+1:

**Comment by richelbilderbeek** [comment]
I have nothing to do now, so I'll assign myself :muscle:

**Comment by richelbilderbeek** [comment]
It *is* a stub:

![Screenshot from 2020-11-10 15-51-28](https://user-images.githubusercontent.com/2098230/98689847-9cdb7400-236c-11eb-8e21-40991e7d1593.png)

Hence: done :+1:
