### ISSUE TITLE
Deploy shiny app according to the shinytest package preferences

### ISSUE THREAD

**Issue by FrieseWoudloper** [informalr/informalr#51]
**[edit by @richelbilderbeek: this is a studying Issue: how can we get our Shiny app on a free website. Below are some options]**

We've got several options for deploying the app: https://shiny.rstudio.com/deploy/

**Comment by richelbilderbeek** [comment]
I agree with the Issue, but it is too early for now. Instead, for starters, the user interface will be a vignette. I will close this Issue until we are ready for something more fancy :+1:

**Comment by richelbilderbeek** [comment]
Nah, put this in its own project :+1:

**Comment by janclod** [comment]
App was deployed following instructions from the shinytest package.
Look here for more info:
https://rstudio.github.io/shinytest/articles/package.html#Application-objects-created-by-functions
