### ISSUE TITLE
Understand and decide for data analysis approach

### ISSUE THREAD

**Issue by fastnotfurious** [informalr/informalr#52]

**Comment by fastnotfurious** [comment]
For example, there is SSD: https://towardsdatascience.com/review-ssd-single-shot-detector-object-detection-851a94607d11

**Comment by fastnotfurious** [comment]
There is R-CNN, Fast R-CNN, Faster R-CNN, YOLO
(Just for a first impression: https://towardsdatascience.com/r-cnn-fast-r-cnn-faster-r-cnn-yolo-object-detection-algorithms-36d53571365e)

**Comment by fastnotfurious** [comment]
Pros and Cons of YOLO (in a nutshell): 

PRO:

- YOLO is orders of magnitude faster(45 frames per second) than other object detection algorithms. 

CONS:

- The limitation of YOLO algorithm is that it struggles with small objects within the image, for example, it might have difficulties in detecting a flock of birds. This is due to the spatial constraints of the algorithm (I believe this is not extremely relevant for the current project, so maybe not such a dramatic downside)

**Comment by fastnotfurious** [comment]
For a fun and easy intro to object detection: https://www.ted.com/talks/joseph_redmon_how_computers_learn_to_recognize_objects_instantly?language=en#t-142736

**Comment by richelbilderbeek** [comment]
I guess we just did so: we'll use (close-to) real-time data from http://opendata.ndw.nu/ and http://opendata.ndw.nu/ .

Can this Issue be closed?

**Comment by richelbilderbeek** [comment]
Issue feels stale. Closing it :+1:
