### ISSUE TITLE
Design the user interface

### ISSUE THREAD

**Issue by FrieseWoudloper** [informalr/informalr#53]
Design the user interface:
- How do we want to interact with the user? 
- How do we want to display the information?

**Comment by richelbilderbeek** [comment]
I agree with the Issue, but it is too early for now. Instead, for starters, the user interface will be a vignette. I will close this Issue until we are ready for something more fancy :+1:

**Comment by richelbilderbeek** [comment]
Nah, put this in its own project :+1:

**Comment by FrieseWoudloper** [comment]
Maybe you will find this tutorial on how to use Leaflet in conjunction with Shiny to interactively visualize geographic information interesting: https://github.com/FrieseWoudloper/shiny-workshop

**Comment by richelbilderbeek** [comment]
I feel this Issue should be cut into separate smaller Issues as well as done later. As the link to the Shiny tutorial is already in the README, I feel this Issue can be closed now :+1:
