### ISSUE TITLE
Build the user interface

### ISSUE THREAD

**Issue by FrieseWoudloper** [informalr/informalr#54]
Build the graphical user interface for the app.

**Comment by richelbilderbeek** [comment]
I agree with the Issue, not with the timing. For now, the user interface will be a vignette. I will close this Issue until we will really create a fancier UI.

**Comment by richelbilderbeek** [comment]
Nah, put this in its own project :+1:

**Comment by richelbilderbeek** [comment]
I feel this Issue should be cut into separate smaller Issues. As the link to the Shiny tutorial is already in the README, I feel this Issue can be closed :+1:
