### ISSUE TITLE
Create first test with shinytest

### ISSUE THREAD

**Issue by FrieseWoudloper** [informalr/informalr#55]
Use the `shinytest` package in addition to `testthat` to create automated tests. https://rstudio.github.io/shinytest/articles/shinytest.html

I only read about `shinytest`, never used it. But I would like to experiment with it.

**Comment by richelbilderbeek** [comment]
@FrieseWoudloper could you try to set 'Projects' to 'Hiking App': the others will love that :+1:

**Comment by richelbilderbeek** [comment]
I've added this Issue to a project :+1:

**Comment by janclod** [comment]
Now that our Shiny app is tested by shinytest, we will have to find out how to test an app that uses dynamic data, as our app.

This is a good starting point:
https://rstudio.github.io/shinytest/articles/in-depth.html#controlling-randomness#dealing-with-dynamic-data

**Comment by richelbilderbeek** [comment]
@janclod I've accepted [your Pull Request](https://github.com/informalr/informalr/pull/117) and I feel this Issue can be closed now. Go ahead and create that new Issue :+1:
