### ISSUE TITLE
Get more background info on NDOV data

### ISSUE THREAD

**Issue by FrieseWoudloper** [informalr/informalr#56]

**Comment by FrieseWoudloper** [comment]
I will contact Stefan de Konink who is an expert on NDOV data.
https://www.linkedin.com/in/skinkie/

**Comment by richelbilderbeek** [comment]
I predict we will manage with the info we can already guess, so I will let it to low priority.

**Comment by richelbilderbeek** [comment]
@FrieseWoudloper what is the status of this Issue?

**Comment by FrieseWoudloper** [comment]
The README.md file in the project root contains a link to the 'NDOV-loket'. I think that is sufficient for now.
