### ISSUE TITLE
Convert available data into usable data sets

### ISSUE THREAD

**Issue by fastnotfurious** [informalr/informalr#57]
Some of the available data are in a really awful excel format and we would need to convert that to make it usable in R; for example http://opendata.ndw.nu/Fietsdata_MRDH/

**Comment by richelbilderbeek** [comment]
Types of data and their Issues:

 * [ ] Bike data, #58 
 * [ ] Bus data, #48

**Comment by richelbilderbeek** [comment]
This Issue feels obsolete now: it has already been divided over more concrete Issues.

Closing this one :+1:
