### ISSUE TITLE
Extract lat/long from XML traffic file

### ISSUE THREAD

**Issue by FrieseWoudloper** [informalr/informalr#61]
How do we extract the latitude en longitude for every bridge in the XML traffic file?
We can't get our code to work.
Latest version of the code: https://github.com/informalr/informalr/blob/willy/R/download_traffic_data.R

**Comment by richelbilderbeek** [comment]
Will progress this on Wednesday/today.

**Comment by richelbilderbeek** [comment]
Didn't do this, went sleeping early today. I'll ask Stefano to work on it next Tuesday :+1:

**Comment by FrieseWoudloper** [comment]
I think I got the solution. The problem was that you have to specify all the namespaces in the xpath statement, also the default ones.

**Comment by FrieseWoudloper** [comment]
See https://github.com/informalr/informalr/blob/willy/R/download_traffic_data.R 
(My branch of the package doesn't pass Travis yet.)

**Comment by FrieseWoudloper** [comment]
Added function get_bridges() to develop with a solution to this problem
