### ISSUE TITLE
test-get_bridges.R generates error: cannot open destfile

### ISSUE THREAD

**Issue by FrieseWoudloper** [informalr/informalr#63]
The current test in test-get_bridge_openings.R generates an error: cannot open destfile './inst/extdata/measurement_current.xml.gz', reason 'No such file or directory'

**Comment by richelbilderbeek** [comment]
Has this error been resolved, or do I really need to take a look?

**Comment by richelbilderbeek** [comment]
Hmm, I read

```
destfile <- "./inst/extdata/measurement_current.xml.gz"
```

Although this is well-intended, there are two problems with this:

  1. The `inst/extdata` folder is for files that are part of the package. Generating files into that folder would be unconventional. Use `rappdirs::user_cache_dir()` to get the platform-independent folder to store temporary files (regarding `rappdirs`: I got this tip from rOpenSci, who do R code reviews)
  2. The use of a relative path `./[stuff]`, which reads as 'from the current path, go into [stuff]' will not work in other settings. To get access to, say, `call_of_cthulu.txt` use, `system.file("extdata", "call_of_cthulhu.txt", package = "informalr")`

I predict this will help resolve this Issue :sunglasses: :+1:

**Comment by richelbilderbeek** [comment]
Well done @janclod !

**Comment by richelbilderbeek** [comment]
@janclod: time to merge it to develop maybe :grin: :+1:
