### ISSUE TITLE
test-create_map generates an error: Unknown graphics device ''

### ISSUE THREAD

**Issue by FrieseWoudloper** [informalr/informalr#64]

**Comment by richelbilderbeek** [comment]
Solution is simple if you know it. This is the test:

```r
  png_filename <- tempfile()
  create_map(png_filename = png_filename)
  expect_true(file.exists(png_filename))
```

`create_map` cannot guess from the variable name `png_filename` alone that it needs to save as a PNG. The error is synonymous with 'I do not know in which image format you want me to write to'.

The fix is easy:

```r
  png_filename <- tempfile(fileext = ".png")
  create_map(png_filename = png_filename)
  expect_true(file.exists(png_filename))
```

**Comment by richelbilderbeek** [comment]
@FrieseWoudloper: I saw this Issue late because it was absent from the 'Hiking App' Project and/or that I was not assigned. If I was irrelevant, sorry for the noise. Else, now you may feel more encouraged to ruthlessly get my attention :+1:
