### ISSUE TITLE
Travis must not download Richel's PhD thesis

### ISSUE THREAD

**Issue by FrieseWoudloper** [informalr/informalr#65]
I think the Travis configuration may need to be updated. See lines 20, 21, 24 en 25 in screenshot.

![image](https://user-images.githubusercontent.com/4244169/93612872-60287780-f9d0-11ea-97a0-9e8ad7ed04e8.png)

**Comment by richelbilderbeek** [comment]
Hmmm, must have been a result of a mass scripting. Let's remove these lines :+1:

**Comment by richelbilderbeek** [comment]
I set this to low priority (it blocks no progress) and put this in 'Getting Started', as this a great beginner Issue.

**Comment by janderkkotlarski** [comment]
Got rid of the lines that download the thesis.
