### ISSUE TITLE
Suggest COVID-19 rules

### ISSUE THREAD

**Issue by richelbilderbeek** [informalr/informalr#66]
Currently, there have been no formal COVID-19 rules. I feel unsure if this what we as a team want.

If you miss a COVID-19 related rule, add it here. We'll vote on these next meeting at #67.

**Comment by richelbilderbeek** [comment]
* 1. No formal rules
 * 2. People of the same pseudo-household (e.g. Frans and Maxime) can group, maintain distance elsewhere. Communication by air (over distance), screen-sharing via Discord and GitHub
 * 3. All people maintain distance. Communication by air (over distance), screen-sharing via Discord and GitHub
 * 4. Move to completely online again

**Comment by richelbilderbeek** [comment]
Assigned all Groningen people, so they can have a look :+1:

**Comment by janderkkotlarski** [comment]
I think these rules are good for the forseeable future, though a tad sad that we then cannot meet irl.

**Comment by swom** [comment]
I vote for 2 or 3

**Comment by janderkkotlarski** [comment]
After reading the issue and the options again and including the new rules the government issued, I have reconsidered what I previously said.

I vote for option 4, thus for fully online gatherings.

**Comment by FrieseWoudloper** [comment]
I think we should move to online for now.

**Comment by richelbilderbeek** [comment]
Closing this Issue. Vote was for mixed IRL+online.
