### ISSUE TITLE
Could not find function "get_jans_github_username"

### ISSUE THREAD

**Issue by FrieseWoudloper** [informalr/informalr#70]
The develop branch - and probably also the jan branch - is broken because of this error:
`could not find function "get_jans_github_username"`
Apparently there is no `get_jans_github_username()` function defined in the package.
Please fix this error.

**Comment by richelbilderbeek** [comment]
Hmmm, this appears done, as when I run the test manually it works:


```r
test_that("use", {
  skip("Function does not exist yet")
  expect_equal("janderkkotlarski", get_jans_github_username())
})
```

@janderkkotlarski: last step is to remove the `skip` line: we skipped the test first to not break the build of the others. As the work has been done (well done :+1:), the `skip` can be removed. This will also increase our code coverage :sunglasses:

**Comment by janderkkotlarski** [comment]
As far as I can see this problem has been solved on my branch.

**Comment by richelbilderbeek** [comment]
Indeed! You can close it :+1:
