### ISSUE TITLE
Add Jan to README.md file

### ISSUE THREAD

**Issue by FrieseWoudloper** [informalr/informalr#72]
@janderkkotlarski is missing in the table listing in the README.md file in the project root.

**Comment by richelbilderbeek** [comment]
Well spotted! I will assign @janderkkotlarski :+1:

**Comment by richelbilderbeek** [comment]
After merging my work to develop, it is already solved:

![Screenshot from 2020-10-08 08-16-27](https://user-images.githubusercontent.com/2098230/95421891-978aa400-093e-11eb-964e-caabeac9342b.png)
![Screenshot from 2020-10-08 08-16-31](https://user-images.githubusercontent.com/2098230/95421897-98bbd100-093e-11eb-9265-e28ec6c74697.png)

Done :+1:
