### ISSUE TITLE
Fix warning: 'no visible binding for global variable 'lon''

### ISSUE THREAD

**Issue by richelbilderbeek** [informalr/informalr#79]
When I run a check, I see two warnings:

![Screenshot from 2020-10-09 13-35-10](https://user-images.githubusercontent.com/2098230/95578505-465cdc00-0a34-11eb-8219-c579e4ec5a98.png)

```
  create_map: no visible binding for global variable ‘lon’
  create_map: no visible binding for global variable ‘lat’
  Undefined global functions or variables:
    lat lon
```

This warning can be fixed by adding this line above the first usage of that variable:

```
my_variable <- NULL; rm(my_variable) # nolint, fixes warning: no visible binding for global variable
```

Do so, for both `lat` and `lon`

**Comment by FrieseWoudloper** [comment]
I still have to merge this fix into develop, after I know for sure that my Travis build went well.

**Comment by FrieseWoudloper** [comment]
Interesting blog post on this issue: https://www.r-bloggers.com/2019/08/no-visible-binding-for-global-variable/

**Comment by FrieseWoudloper** [comment]
Another post, specifically on ggplot2: https://stackoverflow.com/questions/9439256/how-can-i-handle-r-cmd-check-no-visible-binding-for-global-variable-notes-when

**Comment by FrieseWoudloper** [comment]
I would like to try if tidy evaluation provides a more elegant solution to this problem.

**Comment by FrieseWoudloper** [comment]
I would like to give this solution a try: https://fishandwhistle.net/slides/rstudioconf2020/#28

**Comment by richelbilderbeek** [comment]
If that would work, would be great!

**Comment by FrieseWoudloper** [comment]
I finally found a more elegant solution in chapter 12 on tidy evaluation of Hadley Wickham's [Mastering Shiny](https://mastering-shiny.org/action-tidy.html#indirection):

> Data-masking solves the indirection problem in a similar way, by introducing an object, `.data`, that you can subset with either `$` or `[[`. To get started we can rewrite our previous `filter()` call to use `.data` to make it clear that `carat` is a data-variable:
> 
> `diamonds %>% filter(.data$carat > min)`
> This form isn’t particularly useful (**unless you’re writing a package, in which case it eliminates a pesky R CMD check NOTE**), ...

**Comment by FrieseWoudloper** [comment]
Github Actions returns a note :-(
```
create_map: no visible binding for global variable '.data'

Undefined global functions or variables:

  .data
```
