### ISSUE TITLE
Suggest projects

### ISSUE THREAD

**Issue by richelbilderbeek** [informalr/informalr#8]
What do you suggest us to do?

The project with the most votes will win.

**Comment by richelbilderbeek** [comment]
1. A text adventre, as done by @FrieseWoudloper

**Comment by richelbilderbeek** [comment]
* Build `netmhcpan`, an R package that predict which parts of a protein will most likely trigger an immune response. It that calls [NetMHCpan](http://www.cbs.dtu.dk/services/NetMHCpan/), similar to [https://github.com/richelbilderbeek/netmhc2pan](https://github.com/richelbilderbeek/netmhc2pan)

**Comment by richelbilderbeek** [comment]
3. A textadventure, like 1, with a secondary focus on having crime (or other) stories in the newpapers, including graphs. Data from [https://datahub.io/collections](https://datahub.io/collections)

**Comment by MaximBaranov87** [comment]
I like the project #2

**Comment by janclod** [comment]
4. Hiking guide to help hikers spot busy routes/stops before they embark on a hike. This show a somehow similar idea:
![Untitled](https://user-images.githubusercontent.com/6673668/91875429-c0eb4c80-ec7b-11ea-97d1-c0ba5995b089.png)

**Comment by bogeert** [comment]
5-application to rob a Swiss bank and get rich and/or divide the money to the poor.

**Comment by bogeert** [comment]
6-COVID app. Real time see how many COVID-19 cases are in your municipality. Data is available at RIVM https://data.rivm.nl/covid-19/
Data is based on waste water (Rioolwater) and GGD

**Comment by bogeert** [comment]
7-Analyze webcam data to automatically determine the crowdedness of public locations. For example, automatically analyze webcam data from de Groote Markt (https://www.youtube.com/watch?v=ZjfFGJlkjmE) and see if it save to go there within the 1.5m distance rule.

**Comment by bogeert** [comment]
> 
> 
> 7-Analyze webcam data to automatically determine the crowdedness of public locations. For example, automatically analyze webcam data from de Groote Markt (https://www.youtube.com/watch?v=ZjfFGJlkjmE) and see if it save to go there within the 1.5m distance rule.

This is a good package we could use: https://heartbeat.fritz.ai/object-detection-in-just-3-lines-of-r-code-using-tiny-yolo-b5a16e50e8a0

**Comment by FrieseWoudloper** [comment]
8- Recommender that uses predictors like an image, voice recording, time of day, etc. suggests a song by K3 that best matches your mood.

**Comment by bogeert** [comment]
> 
> 
> 8- Recommender that uses predictors like an image, voice recording, time of day, etc. suggests a song by K3 that best matches your mood.

http://thinktostart.com/analyze-face-emotions-r/

**Comment by richelbilderbeek** [comment]
It has become [option 4](https://github.com/informalr/informalr/issues/8#issuecomment-684954585)
