### ISSUE TITLE
Fix style of R/download_traffic_data.R

### ISSUE THREAD

**Issue by richelbilderbeek** [informalr/informalr#80]
Currently, style checking on `R/download_traffic_data.R` is disabled, as it breaks the build. Fix the style of that file.

  1. Remove the part that makes the file be ignored from `.lintr`
  2. Either add-commit-push and see the style errors online, or do `lintr::lint_package()`
  3. Fix the style errors

**Comment by richelbilderbeek** [comment]
I will assign @FrieseWoudloper as she created this (comment-only?) file :+1:

**Comment by FrieseWoudloper** [comment]
Fixed the error, but need to merge it into develop after the build of my branch went well.
