### ISSUE TITLE
Clean GPS coordinates and filter open bridges

### ISSUE THREAD

**Issue by janclod** [informalr/informalr#83]
At the moment the get_bridge_openings function extract the coordinates (long, lat) of bridges.

1. There number of latitude/longitude values is 3872, while the number of values for every situation in the xml file is 1936, something wrong here? Is every bridge represented twice?

Please inspect the xml file (brugopeningen.xml.gz) here:
http://opendata.ndw.nu/
In every field the coordinates are duplicated:
![image](https://user-images.githubusercontent.com/6673668/96628980-3f2aad80-1313-11eb-8255-ac63b2a0f04f.png)

2. at the moment we get the coordinate for all bridges regardless whether they are open or not.

To get more info about the data structure, look here:
https://docs.ndw.nu/nl/sb/brugopeningen/voorbeeld/voorbeeldinterpretatiebrugopening.html

Every bridge should be represented only once and we should find a way to select only open bridges in that specific time.

**Comment by richelbilderbeek** [comment]
@janclod don't forget to add it to the right project. I've done so for you this time :+1:

**Comment by richelbilderbeek** [comment]
@janclod what is the status of this? If this is still a problem, could you write a test that fails?

**Comment by janclod** [comment]
@richelbilderbeek yes, I think that this is still a problem. I will try to write a test next time to expose the issue.

**Comment by janclod** [comment]
@richelbilderbeek I have tried to write the test to expos the issue, see commit  98d6ab8

**Comment by janclod** [comment]
This example should help.

Sample xml file:
`<id>
  <loc1>
    <lat> 60 </lat>
  </loc1>
  <loc2>
    <lat> 60 </lat>
  </loc2>
</id>`

This code does extra the value of latitude only once:
`library("xml2")
# more code to read the xml goes here
xml_find_all(x, ".//loc1//lat")
`
Will this make the test pass?

**Comment by janclod** [comment]
@richelbilderbeek @bogeert @FrieseWoudloper at the moment we get the coordinates of all bridges regardless of their opening status. Is the meaning of this function to simply remain with coordinates of opening bridges?

If this is the case, I would suggest to filter the GPS coordinates based on the <probabilityOfOccurrence> tag. When the tag value is equal to "certain" (bridge likely to open in less than 10 minutes, see here for more info: https://docs.ndw.nu/nl/sb/brugopeningen/voorbeeld/voorbeeldinterpretatiebrugopening.html).

What do you think? :) Happy to hear your feedback!

**Comment by richelbilderbeek** [comment]
@janclod I see your point to only obtain open bridges: it may make things slower. Yet, I [quote Donald Knuth here](https://en.wikiquote.org/wiki/Donald_Knuth):

> premature optimization is the root of all evil (or at least most of it) in programming. 
 
From that, I suggest to keep doing one thing at a time: (1) load all data, (2) filter the data we need. If it can be proven this is a speed bottleneck, we'll optimize it for speed.

**Comment by FrieseWoudloper** [comment]
> xml_find_all(x, ".//loc1//lat")

I changed the code chunk in get_bridge_openings() to
```
    lat <- xml2::xml_text(xml2::xml_find_all(doc, ".//d1:locationForDisplay/d1:latitude", ns))
    lon <- xml2::xml_text(xml2::xml_find_all(doc, ".//d1:locationForDisplay/d1:longitude", ns))
```
Then half of the original records are retrieved. No double entries for the same bridge anymore!
Also I compared running time between the original version of get_bridge_openings() and the new version. The latter is less than 0.1 second slower. So I propose to filter the bridges in the XPath query.

**Comment by FrieseWoudloper** [comment]
@janclod This would be a way to filter out only records with `probabilityOfOccurrence = 'certain'`:

```
    lat <- xml2::xml_text(xml2::xml_find_all(doc, ".//d1:situationRecord[d1:probabilityOfOccurrence/text() = 'certain']/d1:groupOfLocations/d1:locationForDisplay/d1:latitude", ns))
    lon <- xml2::xml_text(xml2::xml_find_all(doc, ".//d1:situationRecord[d1:probabilityOfOccurrence/text() = 'certain']/d1:groupOfLocations/d1:locationForDisplay/d1:longitude", ns))
```

**Comment by janclod** [comment]
@FrieseWoudloper great! thanks for teaching me how to filter data, I was struggling quite a lot last time, trying to figure this out.

@richelbilderbeek is this really optimization? I mean if the function needs to return opening bridges, it should do so, right? Anyway it is a good point you are making about early optimization, could you talk about it a bit more here or next Tuesday? Thanks!

**Comment by richelbilderbeek** [comment]
> @richelbilderbeek is this really optimization? I mean if the function needs to return opening bridges, it should do so, right? Anyway it is a good point you are making about early optimization, could you talk about it a bit more here or next Tuesday? Thanks!

@janclod: I feel it is an optimization, because we make one function do two things, which are (1) download data, (2) filter data. It is usually better to have one function to do one thing. OTOH. I see no need to be too rigid in this: when doing both steps with one regular expression is fine as well :+1:

**Comment by janclod** [comment]
I have incorporated @FrieseWoudloper's code :+1:
