### ISSUE TITLE
replace ggmap by tmap

### ISSUE THREAD

**Issue by FrieseWoudloper** [informalr/informalr#87]
I think ggmap might be more or less outdated and should be replaced, for instance by tmap/tmaptools.
I would like to try and do this, also to see if I can change the implementation of the create_map function without breaking any other code.

**Comment by richelbilderbeek** [comment]
It is doable:

```{r}
expect_silent(create_map(plotting_engine = "tmap"))
```
```

**Comment by FrieseWoudloper** [comment]
This is *much*  shorter than the original chunk of code: ` tmap::qtm("Groningen")`
But it generates a Leaflet app, not a png.

**Comment by FrieseWoudloper** [comment]
I close this issue, because create_map_viewer.R already contains an example of an interactive map viewer using the Leaflet JavaScript library. It is created with the leaflet package in stead of qtm.
