### ISSUE TITLE
Redundant code in create_map and plot_bridge_openings

### ISSUE THREAD

**Issue by FrieseWoudloper** [informalr/informalr#88]
There is redundant code in `create_map` and `plot_bridge_openings`. I think we need to refactor the code and do three things:
1 Get a basemap
2 Plot one or more thematic maps on top of the base map
3 Save the complete map to a file.

`plot_bridge_openings` would execute these three functions with the dataset with bridge openings as an argument in the second step.

**Comment by richelbilderbeek** [comment]
Well spotted!

**Comment by richelbilderbeek** [comment]
I assign Geert and Willy to discuss this first and let this be fixed :+1:

**Comment by FrieseWoudloper** [comment]
Redundant code has been removed.
