### ISSUE TITLE
Pick specific two- or three-hour timeslot

### ISSUE THREAD

**Issue by richelbilderbeek** [informalr/informalr#9]
In #2 we narrowed down when we'll meet. Question is, how long and when will we meet exactly?

Procedure: rate the timeslots: rating: 3 = awesome, 2 = OK, 1 = meh. Highest sums gets it

For example:

 * Tuesday 17:00-19:00: 2
 * Tuesday 18:00-20:00: 3
 * Tuesday 17:00-20:00: 2

Pick from:

 * Tuesday 17:00-19:00 (2 hours)
 * Tuesday 18:00-20:00 (2 hours)
 * Tuesday 17:00-21:00 (3 hours)

**Comment by richelbilderbeek** [comment]
My votes:

 * Tuesday 17:00-19:00: 3
 * Tuesday 18:00-20:00: 3
 * Tuesday 19:00-21:00: 2

**Comment by fastnotfurious** [comment]
Anne's votes:

    Tuesday 17:00-19:00: 2
    Tuesday 18:00-20:00: 3
    Tuesday 17:00-21:00: 1

**Comment by AparajithaRamesh** [comment]
Apu's votes:

Tuesday 17:00-19:00: 3
Tuesday 18:00-20:00: 3
Tuesday 17:00-21:00: 1

**Comment by bogeert** [comment]
Geert's votes:

    Tuesday 17:00-19:00: 1
    Tuesday 18:00-20:00: 3
    Tuesday 17:00-21:00: 2

**Comment by FrieseWoudloper** [comment]
Tuesday 17:00-19:00 (2 hours): 1
Tuesday 18:00-20:00 (2 hours): 3
Tuesday 17:00-21:00 (3 hours): 2

**Comment by richelbilderbeek** [comment]
Harry's votes:

 * Tuesday 17:00-19:00: 3
 * Tuesday 18:00-20:00: 0
 * Tuesday 17:00-21:00: 0

**Comment by Lizzie-Roeble** [comment]
Tuesday 17:00-19:00: 3
Tuesday 18:00-20:00: 1
Tuesday 17:00-20:00: 1

**Comment by Neves-P** [comment]
Tuesday 17:00-19:00: 2
Tuesday 18:00-20:00: 3
Tuesday 17:00-20:00: 1

**Comment by MaximBaranov87** [comment]
no preference

**Comment by richelbilderbeek** [comment]
Conclusion:

 * Tuesday 18:00-20:00

Note that one can always attend for just one hour, as well as we can opt for a more diffuse team as well...
