### ISSUE TITLE
Use function call to multiply_four_numbers as argument for expect_equal

### ISSUE THREAD

**Issue by FrieseWoudloper** [informalr/informalr#92]
I accidentally broke `multiply_four_numbers`. I would have noticed it if the `expect_equal` test would have had `multiply_four_numbers(2, 2, 2, 2)` as argument in stead of `2 * 2 * 2 * 2`. 

So you may want to change this code chunk:

```
test_that("multiplication works", {       
  expect_equal(2 * 2 * 2 * 2, 16)    
})    
```

**Comment by richelbilderbeek** [comment]
Well done! Closing it already :+1:
